---
name: 'app-service-configurable'
version: '1.3.0'
releaseName: 'hanoi'
releaseStream: 'master'
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/docker-app-service-configurable
      - docker.io/edgexfoundry/docker-app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/docker-app-service-configurable-arm64
      - docker.io/edgexfoundry/docker-app-service-configurable-arm64