---
name: 'app-service-configurable'
version: '2.0.1'
releaseName: 'ireland'
releaseStream: 'main'
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: 'a8794a006ea08968641ff6a1a2acb87b2eaa877d'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable
      - docker.io/edgexfoundry/app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable-arm64
      - docker.io/edgexfoundry/app-service-configurable-arm64

