---
name: 'app-service-configurable'
version: '2.0.0'
releaseName: 'ireland'
releaseStream: 'master'
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: 'b6f81afb00c623cfafb3d4c5994f810f91048a0e'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable
      - docker.io/edgexfoundry/app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable-arm64
      - docker.io/edgexfoundry/app-service-configurable-arm64

