---
name: 'app-service-configurable'
version: '1.3.1'
releaseName: 'hanoi'
releaseStream: 'hanoi'
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: '072b184390152c35aa93e82d9a3e94daf634685c'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/docker-app-service-configurable
      - docker.io/edgexfoundry/docker-app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/docker-app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/docker-app-service-configurable-arm64
      - docker.io/edgexfoundry/docker-app-service-configurable-arm64