---
name: 'app-service-configurable'
version: '2.2.0'
releaseName: 'kamakura'
releaseStream: 'main'
repo: 'https://github.com/edgexfoundry/app-service-configurable.git'
commitId: '1aebe0375d702ec5557b529d86506036d5612df5'
gitTag: true
dockerImages: true
docker:
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable
      - docker.io/edgexfoundry/app-service-configurable
  - image: nexus3.edgexfoundry.org:10004/app-service-configurable-arm64
    destination:
      - nexus3.edgexfoundry.org:10002/app-service-configurable-arm64
      - docker.io/edgexfoundry/app-service-configurable-arm64