---
name: 'go-mod-configuration'
version: '2.1.0'
releaseName: 'jakarta'
releaseStream: 'main'
lts: true
repo: 'https://github.com/edgexfoundry/go-mod-configuration.git'
commitId: '53230280edfc871ff53ec5eb8cb7b2f03142bb4d'
gitTag: true
dockerImages: false