---
name: 'go-mod-configuration'
version: '2.2.0'
releaseName: 'kamakura'
releaseStream: 'main'
repo: 'https://github.com/edgexfoundry/go-mod-configuration.git'
commitId: 'd782c4d625d7b267303ff1fbcd6dbbbf7629934f'
gitTag: true
dockerImages: false